### ISSUE TITLE
ElasticAdapter\Search\Bucket->key() must not assert "string" as return value

### ISSUE THREAD

**Issue by janoppor** [babenkoivan/elastic-adapter#19]
**Describe the bug**
If you do an aggregation in your Elastic query on a integer value you will not be able to get the key of the buckets back. Please remove the ": string" after the method definition of Bucket->key() or set as a mixed value

**To Reproduce**
You just need an index with an integer value and do an aggregation to it. You will receive the Bucket and you will not be able to get the value, because the assertion of string to the return value is assigned:
ElasticAdapter\Search\Bucket->key() on integer

**Current behavior**
PHP Error

**Expected behavior**
Integers and maybe other types should be possible to get back in a bucket

**Comment by babenkoivan** [comment]
@janoppor thank you for reporting a bug! This is now resolved in [v2.1.0](https://github.com/babenkoivan/elastic-adapter/releases/tag/v2.1.0) 🙂
