### ISSUE TITLE
ES 7.X / opensearch 1.1 support to be support the new false default for`include_type_name` 

### ISSUE THREAD

**Issue by sdbruder** [babenkoivan/elastic-adapter#25]
| Software        | Version
| ------------- | ---------------
| PHP                | 8.1.3 and 8.0.13
| Opensearch | 1.1 

**Describe the bug**
Cannot update indexes using elastic-migrations as there is no way to set XXX to true, causing this error:
```
{
    "error": {
        "root_cause": [{
            "type": "illegal_argument_exception",
            "reason": "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
        }],
        "type": "illegal_argument_exception",
        "reason": "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
    },
    "status": 400
}
```

**To Reproduce**
Try to update an index on a recent-enough ES where include_type_name now defaults to false.

**Current behavior**
Now index updates are failing

**Expected behavior**
Correct behaviour of  index updates or a way to pass additional parameters to `IndexManager::putMappings`'s call to `$this->indices->putMapping([]);`

**Comment by babenkoivan** [comment]
Hi @sdbruder, what versions of `elastic-migrations` and `elastic-adapter` do you use? Have you tried to update to the latest versions? `elastic-adapter` doesn't provide types for a very long time, there should be no need to set `include_type_name` to true.
