### ISSUE TITLE
Buckets support pluck

### ISSUE THREAD

**Issue by nick322** [babenkoivan/elastic-adapter#26]
Aggregate after has many buckets.
I need retrieve a list of specific values from a bucket. 
[#27](https://github.com/babenkoivan/elastic-adapter/pull/27)

**Comment by babenkoivan** [comment]
Hi @nick322, thank you for your contribution! 
I plan to make all entities that implement `RawResponseInterface` accessible as arrays in the next major update.

**Comment by nick322** [comment]
Hi @babenkoivan ,thank you for your reply. Do I need to change the code on the PR directly?

```php
interface RawResponseInterface extends \ArrayAccess
{...
```

**Comment by babenkoivan** [comment]
Hey @nick322, sorry for taking that long to respond. You don't need to change the PR, this feature is coming in the future release, hopefully before autumn.

**Comment by babenkoivan** [comment]
Hey @nick322, this feature is now available in [v3.0.0](https://github.com/babenkoivan/elastic-adapter/releases/tag/v3.0.0)! You can see the usage example [here](https://github.com/babenkoivan/elastic-adapter/blob/50e9559774c09688a0f5024c964ab22b97c554de/tests/Unit/Search/AggregationTest.php#L47). Please note, that the new version supports only ES8 and contains some breaking changes.
