### ISSUE TITLE
Please add php 8 support

### ISSUE THREAD

**Issue by e-yakubov** [babenkoivan/elastic-adapter#3]
Could you update composer.json ?

**Comment by babenkoivan** [comment]
This package relies on `elasticsearch/elasticsearch`, which doesn't support php 8 yet.

**Comment by alpar-lorincz** [comment]
> 
> 
> This package relies on `elasticsearch/elasticsearch`, which doesn't support php 8 yet.

It was introduced here: https://github.com/elastic/elasticsearch-php/tree/7.x

Could you please provide something similar? I already have the elastic-migrations, elastic-scout-driver and elastic-scout-driver-plus working with PHP 8.0 on my forked versions, but cannot add them untill we have an updated adapter.

**Comment by philipnewcomer** [comment]
@babenkoivan `elasticsearch/elasticsearch` now supports PHP 8 in their most recent public release: https://github.com/elastic/elasticsearch-php/releases/tag/v7.11.0

**Comment by babenkoivan** [comment]
PHP 8 support was added in [v1.13.0](https://github.com/babenkoivan/elastic-adapter/releases/tag/v1.13.0)  🎉
