### ISSUE TITLE
Missing a way to set _routing and other available index params

### ISSUE THREAD

**Issue by spiritinlife** [babenkoivan/elastic-adapter#8]
There should be a way to specify the `_routing` option.
Probably it would be best to make this more generic and give a way to set all [these available params](https://github.com/elastic/elasticsearch-php/blob/6c9c0a765f8b31c1d9f1a5af4de2f53fd7298e38/src/Elasticsearch/Client.php#L766-L785)

**Comment by babenkoivan** [comment]
The related PR is merged.
